### PR TITLE
PHR-12405 Add global configuration option for restricting to test-range NHS numbers

### PR DESCRIPTION
**Pull request by MFAshby**

### CODE REVIEW

**Review by pkbdevdeploy — COMMENTED** [review]
Version `64-head-d4dbd45-303847-SNAPSHOT` was generated from commit `d4dbd45320e124ec1979e7e383d7002478f695f0`

**Review by jimmymcfox — APPROVED** [review]
LGTM

**Review by pkbdevdeploy — COMMENTED** [review]
Version `64-head-a30d45d-304649-SNAPSHOT` was generated from commit `a30d45d33b1b76c4564fff5a1e4c1036627a97d3`

**Review by jimmymcfox — APPROVED** [review]
Thanks for removing PkbConfig

**Comment by MFAshby** [comment]
I'm going to do this another way.

**Pull request closed without merging**
