### PR TITLE
PHR-12042 Tidy up some dependencies to help with spring boot transition in PHR

### PR DESCRIPTION
**Pull request by MFAshby**

### CODE REVIEW

**Review by pkbdevdeploy — COMMENTED** [review]
Version `66-head-8f79a3f-341404-SNAPSHOT` was generated from commit `8f79a3fe148a8ccacd0d528d57766407f78e276d`

**Review by idasbiste — COMMENTED** [review]
I think we already hit this OWASP issue in `phr` and we had to exclude it because even by upgrading/pinning netty to the latest version would not make it go away. Otherwise it looks good 👍

**Comment by idasbiste** [comment]
Feel free to update/rebase because #101 was just merged and that suppresses the issue that this one is flagging.

**Comment by MFAshby** [comment]
Thanks @idasbiste will do

**Comment by MFAshby** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

yes, the number of hours in the day is too small. But I can't change that, dependabot. I really can't.

**Review by pkbdevdeploy — COMMENTED** [review]
Version `69-head-a965bc6-369082-SNAPSHOT` was generated from commit `a965bc6599f30d1a1493ec723b00ffb79af1f6ce`

**Comment by idasbiste** [comment]
There are still OWASP failures with this one although we suppress it or pin latest versions in `phr` where this library is only (?) used.

**Comment by MFAshby** [comment]
> There are still OWASP failures with this one although we either suppress them or pin latest versions in phr where this library is only (?) used.

Yeah I don't think it's actually worth having OWASP check on this repo, since dependencies are scanned recursively in PHR!

**Review by idasbiste — COMMENTED** [review]
We might still want this, yes; the Spring Boot transition PR is https://github.com/patientsknowbest/phr/pull/7974

**Review by pkbdevdeploy — COMMENTED** [review]
Version `70-head-868f435-389895-SNAPSHOT` was generated from commit `868f4351972edbf08c4185be0946038012064334`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `70-5ba0055-401136` was generated from commit `5ba005557b325f9f98846699b3e017f1698c7175`

**Pull request merged**
