### PR TITLE
Update owasp version

### PR DESCRIPTION
**Pull request by utamas**

### CODE REVIEW

**Review by symposion — APPROVED** [review]
LGTM, thanks!

**Review by pkbdevdeploy — COMMENTED** [review]
Version `68-head-aa672cd-358574-SNAPSHOT` was generated from commit `aa672cd71d48d149767d471f738307724e63fa96`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `68-head-aa672cd-358590-SNAPSHOT` was generated from commit `aa672cd71d48d149767d471f738307724e63fa96`

**Review by idasbiste — APPROVED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `68-27ab7f3-358594-SNAPSHOT` was generated from commit `27ab7f32aaa45ec826b29977b96a0c989896dc4c`

**Pull request merged**
