### PR TITLE
Bump version of commons-test PHR-10426

### PR DESCRIPTION
**Pull request by RaphaelColman**

### CODE REVIEW

**Review by idasbiste — APPROVED** [review]

**Review by adrns — APPROVED** [review]

**Review by karsaig — DISMISSED** [review]

**Review by adrns — APPROVED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `59-head-45d7372-247842-SNAPSHOT` was generated from commit `45d7372ac6d68018fae04d9db58a574346caa06b`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `59-head-7c0c272-248434-SNAPSHOT` was generated from commit `7c0c27293977564b115866841164bd179b8a1bc9`

**Review by adrns — APPROVED** [review]

**Review by karsaig — APPROVED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `59-e3fa304-248450-SNAPSHOT` was generated from commit `e3fa304c8d1ce9c8ca209535a9c44ed0d0974587`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `create-e3fa304-248465` was generated from commit `e3fa304c8d1ce9c8ca209535a9c44ed0d0974587`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `create-e3fa304-248467` was generated from commit `e3fa304c8d1ce9c8ca209535a9c44ed0d0974587`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `create-e3fa304-248468` was generated from commit `e3fa304c8d1ce9c8ca209535a9c44ed0d0974587`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `59-e3fa304-248476` was generated from commit `e3fa304c8d1ce9c8ca209535a9c44ed0d0974587`

**Pull request merged**
