### PR TITLE
Change FakeDateTimeService to return wrapper clock

### PR DESCRIPTION
**Pull request by symposion**
Allows for injecting a mockable clock into classes that take a clock as a constructor parameter

### CODE REVIEW

**Review by idasbiste — COMMENTED** [review]
The changes look good; what is the use case triggering these?

**Review by homps — DISMISSED** [review]

**Comment by symposion** [comment]
> The changes look good; what is the use case triggering these?

https://github.com/patientsknowbest/phr/pull/6953 -> I need to inject a clock into a Spring security component that takes it as a constructor parameter and holds onto it, so it needs to respond dynamically to changes in the DateTimeService rather than being determined by the state of the DTS at the point you ask for the clock

**Review by pkbdevdeploy — COMMENTED** [review]
Version `62-head-ff4847c-302061-SNAPSHOT` was generated from commit `ff4847cc0198b155d0c950fc8448e8c619fa17c3`

**Review by idasbiste — APPROVED** [review]

**Review by homps — APPROVED** [review]

**Comment by symposion** [comment]
Corresponding PHR PR has passed now, I think this might as well be merged now

**Review by homps — APPROVED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `63-9c8e1da-302841` was generated from commit `9c8e1da5e9bcc652e7191b52202988aed9f49ba6`

**Pull request merged**
