### PR TITLE
Tidy up some dependencies to help with spring boot transition in PHR

### PR DESCRIPTION
**Pull request by symposion**

### CODE REVIEW

**Review by pkbdevdeploy — COMMENTED** [review]
Version `62-head-0c704fd-300452-SNAPSHOT` was generated from commit `0c704fd56f2b4877ac104a5f17ae1b797154cdf5`

**Review by idasbiste — COMMENTED** [review]
OWASP seems unhappy for some reason but upgrading it to 8 wouldn't do harm. Otherwise looks fine.

**Review by homps — DISMISSED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `65-head-ee57fd4-314641-SNAPSHOT` was generated from commit `ee57fd4fb8b634eba7e2f81270c5cd1f166b4a17`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `65-head-acd8716-322548-SNAPSHOT` was generated from commit `acd8716bd17acf67032fe1e89cfac73c72907bee`

**Comment by symposion** [comment]
Closing for Martin to reopen when ready

**Pull request closed without merging**
