### PR TITLE
PHR-14129 Stop using ToStringBuilder#reflectionToString because it doesn't work in JDK17

### PR DESCRIPTION
**Pull request by MFAshby**
https://issues.apache.org/jira/browse/LANG-1685
PHR-14129

### CODE REVIEW

**Review by pkbdevdeploy — COMMENTED** [review]
Version `71-head-3a4e8c8-406957-SNAPSHOT` was generated from commit `3a4e8c8d55bf255bea6db83268a1e0d35d341944`

**Review by dorogimate — APPROVED** [review]
LGTM

**Review by alyssaruth — APPROVED** [review]

**Comment by MFAshby** [comment]
build finished, I don't know why github thinks it didn't.

**Review by pkbdevdeploy — COMMENTED** [review]
Version `71-3897f71-407464` was generated from commit `3897f7144dfb3aa364ca74c0de0a38b1c4bca348`

**Pull request merged**
