### PR TITLE
Bump deps and add suppression for OWASP

### PR DESCRIPTION
**Pull request by symposion**

### CODE REVIEW

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-head-a44dfd8-352058-SNAPSHOT` was generated from commit `a44dfd866b17b3db4e253c5fc431d3736c80d521`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-head-67935ec-352225-SNAPSHOT` was generated from commit `67935ec29e59ec7c4f8495a2a014b0d0db200bfb`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-head-859bfa8-352228-SNAPSHOT` was generated from commit `859bfa87b6e3d9061928ae4fc2db8bab441987e4`

**Review by MFAshby — COMMENTED** [review]
LGTM pending bump from snapshot -> released version

**Review by r-oylo — COMMENTED** [review]
looks good provided we change the snapshot versino

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-head-8fd911d-352337-SNAPSHOT` was generated from commit `8fd911df4bc6fee8c0df44cde64c495b25c8cc45`

**Review by r-oylo — APPROVED** [review]
looks good!

**Review by MFAshby — APPROVED** [review]

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-4c5f470-352341-SNAPSHOT` was generated from commit `4c5f470c6d17a56bfccdb3abd90373686077db1c`

**Review by pkbdevdeploy — COMMENTED** [review]
Version `67-4c5f470-352350` was generated from commit `4c5f470c6d17a56bfccdb3abd90373686077db1c`

**Pull request merged**
